name: (â–¶) Create Release

on: workflow_dispatch

jobs:
    release:
        uses: sitepark/github-project-workflow/.github/workflows/composer-release.yml@release/1.x
        with:
            botName: "sitepark-bot"
            botEmail: "opensource@sitepark.com"
            phpVersion: "8.4"
        secrets:
            # Sitepark-BOT personal access token
            BOT_PAT: ${{ secrets.BOT_PAT }}
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
